const APP_CONFIG = {
  SPREADSHEET_ID: "1_TgRfzkYaj47j1Ci5EqFQsQUlMnH_yY7bmwvCQdp9_k",
  SHEETS: {
    ACCESOS: "accesos",
    SESIONES: "sesiones",
    RESPUESTAS: "respuestas",
    RESULTADOS: "resultados"
  },
  SESSION_HOURS: 6
};

const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCESS_INACTIVE: "ACCESS_INACTIVE",
  ACCESS_EXPIRED: "ACCESS_EXPIRED",
  ACCESS_BLOCKED: "ACCESS_BLOCKED",
  SESSION_INVALID: "SESSION_INVALID",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
};
